title: Simplex Via LLC Website
description: Documentation for Simplex Via website 
baseurl: "/cs-website"
url: "https://simplexvia.github.io" 
theme: jekyll-theme-primer
markdown: GFM
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-gist
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
relative_links:
  enabled: true
  collections: true
include:
  - "*.md"
  - docs/horseman/index.md
  - docs/horseman/horse-corerction-guide.md
  - docs/horseman/gloreyous-tomcat-eval.md
  - docs/horseman/horse-buying-guide-v2.md
  - docs/horseman/horse-buying-guide-family.md
  - docs/horseman/forged-arrow-eval.md
  - docs/horseman/horse-buying-guide.md
  - docs/cloudnative-tools/index.md
  - docs/cloudnative-tools/jenkins-upgrade-triage-guide.md
  - docs/cloudnative-tools/oss-tf-execution-slides.md
  - docs/cloudnative-tools/oss-tf-execution-comparison.md
  - "CONTRIBUTING.md"
  - "README.md"
  - "LICENSE.md"
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
permalink: pretty
source: docs
verbose: true